name: build

on:
  pull_request:
    branches: [master, main]
  push:
    branches: ["*"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  # copied from MCGalaxy
  build:
    runs-on: ubuntu-22.04
    env:
      BUILD_CONFIGURATION: ${{ startsWith(github.ref, 'refs/tags/') && 'Release' || 'Debug' }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: msbuild ./MCGalaxy-Relay-Plugin.sln /p:Configuration=Release /p:TargetFrameworkVersion=v2.0 /p:DefineConstants="NET_20"

      - uses: actions/upload-artifact@v4
        with:
          name: MCGalaxy-Relay-Plugin
          path: MCGalaxy-Relay-Plugin/bin/${{ env.BUILD_CONFIGURATION }}/MCGalaxy-Relay-Plugin.dll

      - uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: MCGalaxy-Relay-Plugin/bin/${{ env.BUILD_CONFIGURATION }}/MCGalaxy-Relay-Plugin.dll
