name: build

on:
  pull_request:
    branches: [master, main]
  push:
    branches: ["*"]
    tags: ["*"]
  workflow_dispatch:

permissions:
  contents: write # for checkout, upload-artifact, and action-gh-release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v31

      - run: |
          nix build '.?submodules=1#default' \
            --print-build-logs --no-update-lock-file

      - uses: actions/upload-artifact@v4
        with:
          name: MCGalaxy-Relay-Plugin
          path: result/lib/MCGalaxy-Relay-Plugin.dll

      - uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: result/lib/MCGalaxy-Relay-Plugin.dll
